<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="usemearch" nsURI="http://mem4cds.telecom-paristech.fr/languages/usemearch/"
    nsPrefix="usemearch">
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentSpecification" eSuperTypes="#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDsls" lowerBound="1"
        upperBound="-1" eType="#//Dsl" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTools" lowerBound="1"
        upperBound="-1" eType="#//Dsl" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnvironmentalElement" abstract="true"
      eSuperTypes="#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="envitonmentType" eType="#//EnvironmentType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EnvironmentType">
    <eLiterals name="Technical"/>
    <eLiterals name="Physical" value="1"/>
    <eLiterals name="Social" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextSpecification" eSuperTypes="#//IdentifiedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="developedDsl" lowerBound="1"
        eType="#//Dsl"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environmentalElements"
        lowerBound="1" upperBound="-1" eType="#//EnvironmentalElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dsl" eSuperTypes="#//EnvironmentalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSyntaxes" lowerBound="2"
        upperBound="-1" eType="#//Syntax" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="concreteSyntaxes" lowerBound="1"
        upperBound="-1" eType="#//ConcreteSyntax" changeable="false" volatile="true"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractsyntax" lowerBound="1"
        eType="#//AbstractSyntax" changeable="false" volatile="true" transient="true"
        derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportingTools" upperBound="-1"
        eType="#//SoftwareTool" eOpposite="#//SoftwareTool/supportedLanguages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Syntax" abstract="true" eSuperTypes="#//IdentifiedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractSyntax" abstract="true" eSuperTypes="#//Syntax"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConcreteSyntax" abstract="true" eSuperTypes="#//Syntax">
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" eType="ecore:EClass ../../fr.labsticc.framework.constraints.model/model/constraints.ecore#//NaturalConstraintLanguage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ECoreAbstractSyntax" eSuperTypes="#//AbstractSyntax">
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SiriusConcreteSyntax" eSuperTypes="#//ConcreteSyntax">
    <eStructuralFeatures xsi:type="ecore:EReference" name="siriusSpecification" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.sirius/model/viewpoint.ecore#//description/Group"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tool" abstract="true" eSuperTypes="#//EnvironmentalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedBy" lowerBound="1"
        upperBound="-1" eType="#//User"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//EnvironmentalElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" lowerBound="1" upperBound="-1"
        eType="#//Tool"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkPlace" eSuperTypes="#//EnvironmentalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Computer" eSuperTypes="#//Tool"/>
  <eClassifiers xsi:type="ecore:EClass" name="SoftwareTool" eSuperTypes="#//Tool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedLanguages" lowerBound="1"
        upperBound="-1" eType="#//Dsl" eOpposite="#//Dsl/supportingTools"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingSystem" eSuperTypes="#//SoftwareTool"/>
</ecore:EPackage>
